export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD = 'ADD'
export const SUBTRACT = 'SUBTRACT'
export const ADDRESULTS = 'ADDRESULTS'
export const DELETE = 'DELETE'